[build]
builder = "COMPOSE"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Настройки для Streamlit приложения
[[services]]
name = "streamlit_app"
type = "web"
port = 8501
domain = "task-tracker-ui"

# Настройки для FastAPI приложения
[[services]]
name = "app"
type = "web"
port = 8080
domain = "task-tracker-api"

# Настройки для PostgreSQL (дополнительная база данных от Railway)
[[services]]
name = "postgres"
type = "postgresql"
plan = "hobby"

# Настройки для Redis (дополнительный кэш от Railway)
[[services]]
name = "redis"
type = "redis"
plan = "hobby"

# Переменные окружения
[variables]
# Database
POSTGRES_USER = "myapp_user"
POSTGRES_PASSWORD = "myapp_password"
POSTGRES_DB = "myapp"
POSTGRES_HOST = "db_postgres"
POSTGRES_PORT = 5432

# Redis
REDIS_HOST = "redis"
REDIS_PORT = 6379

# Streamlit
API_BASE_URL = "http://app:8080"

# JWT (добавьте эти настройки для безопасности)
JWT_SECRET_KEY = "change-this-to-very-secret-key-in-production"
JWT_ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 15
REFRESH_TOKEN_EXPIRE_DAYS = 7